FROM python:3.13.13
MAINTAINER Komal Thareja<komal.thareja@gmail.com>

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
VOLUME ["/usr/src/app"]

EXPOSE 11000

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN apt-get update
RUN apt-get install cron -y

COPY docker-entrypoint.sh /usr/src/app/
COPY fabric_cf /usr/src/app/fabric_cf
COPY pyproject.toml /usr/src/app/
COPY README.md /usr/src/app/
COPY LICENSE /usr/src/app/
COPY tools/audit.py /usr/src/app/
COPY tools/export.py /usr/src/app/
COPY tools/install.sh /usr/src/app/

RUN pip install .
RUN mkdir -p "/etc/fabric/message_bus/schema"
RUN mkdir -p "/etc/fabric/actor/config"
RUN mkdir -p "/var/log/actor"
RUN cp /opt/venv/lib/python3.13/site-packages/fabric_mb/message_bus/schema/*.avsc /etc/fabric/message_bus/schema
RUN sh /usr/src/app/install.sh

ENTRYPOINT ["/usr/src/app/docker-entrypoint.sh"]
CMD ["fabric_cf.broker"]
